FROM python:3.7

RUN pip install requests pandas numpy
RUN touch /input.txt
RUN touch /output.txt

CMD ["echo", "You need to build an application on top of this image, including a CMD specification of your execution."]